### ISSUE TITLE
Clobbered existing package in PyPi

### ISSUE THREAD

**Issue by heston** [browserstack/browserstack-local-python#13]
Hey Browserstack folks,

Not sure if you realized this, but when you pushed this package to PyPi, you clobbered an existing package name, [browserstack-local](https://pypi.python.org/pypi/browserstack-local/0.2). You also used a version signifying that you were making a backwards-compatible change to the existing package (see [semver](http://semver.org/)). Not only is this an entirely different package, it's also incompatible with the one already released (e.g. different namespaces; different API).

I think it's generally not good etiquette to clobber packages in PyPi, even if the purpose is similar. It took us half a day to track down our failing integration tests to this release.

I would encourage you to either pick another package name, or do a major version bump (e.g. 1.0) to indicate that this is a backwards incompatible change.

Thank you.

**Comment by tr4n2uil** [comment]
Hey heston,

Thanks for pointing this out. We have bumped our version to v1.0.0 now. 
We have published the enhanced version of local bindings, and we recommend you to use this newer API, which would be supported officially by BrowserStack.

Thanks
