### ISSUE TITLE
Unable to set local binary path

### ISSUE THREAD

**Issue by rfboykin** [browserstack/browserstack-local-python#19]
Hey, setting the local binary path with the "binarypath" option leads to an error: 
"NameError: global name 'binary_path' is not defined"

The culprit seems to be this block in local.py

> if 'binarypath' in self.options:
> &nbsp;&nbsp;&nbsp;&nbsp;self.binary_path = binary_path
>&nbsp;&nbsp;&nbsp;&nbsp;del self.options['binarypath']
>  else:
> &nbsp;&nbsp;&nbsp;&nbsp;self.binary_path = LocalBinary().get_binary()

I believe changing the second line to `self.binary_path = self.options['binarypath']` will fix this issue.

Please fix or let me know if there is another solution. 

Thank you!

**Comment by bipul21** [comment]
Hey, 
Thanks for pointing this out. We will be deploying the fix in some time and let you know.

**Comment by bipul21** [comment]
Updated. 

You can update your package with pip install -U browserstack-local
